import { Raleway, Red_Hat_Display, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import SmoothScrollWrapper from "@/Components/SmoothScrollWrapper";

// Google Fonts
const robotoMono = Roboto_Mono({ variable: "--font-roboto-mono", subsets: ["latin"] });
const raleway = Raleway({ variable: "--font-raleway", subsets: ["latin"] });
const redhatdisplay = Red_Hat_Display({ variable: "--font-redhatdisplay", subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${robotoMono.variable} ${raleway.variable} ${redhatdisplay.variable}`}
        suppressHydrationWarning
      >
        <body className="font-redhat antialiased" suppressHydrationWarning>
          <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
        </body>
      </html>
    </ViewTransitions>
  );
}
