import { Geist, Geist_Mono,Raleway,Red_Hat_Display } from "next/font/google";
import "./globals.css";
import Clientnavbar from "@/Components/Clientnavbar"; // this is a client component
import SmoothScroll from "@/Components/SmoothScroll";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
})

const redhatdisplay = Red_Hat_Display({
  variable: "--font-redhatdisplay",
  subsets: ["latin"],
})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
   
    <html lang="en">
      <body className={`font-redhat antialiased`}>
        <Clientnavbar />
        <div>{children}</div>
      </body>
    </html>
   
  );
}
