import { Geist, Geist_Mono, Raleway, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import SmoothScrollWrapper from "@/Components/SmoothScrollWrapper";

// Google Fonts
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const raleway = Raleway({ variable: "--font-raleway", subsets: ["latin"] });
const redhatdisplay = Red_Hat_Display({ variable: "--font-redhatdisplay", subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${redhatdisplay.variable}`}
        suppressHydrationWarning
      >
        <body className="font-redhat antialiased" suppressHydrationWarning>
          <SmoothScrollWrapper>{children}</SmoothScrollWrapper>
        </body>
      </html>
    </ViewTransitions>
  );
}
